#!/usr/bin/env python3
"""Extract Tableau Public links from ``posts/*.html`` into stable maps."""
import os
import re
import csv
import glob
import json
from collections import Counter

PROJECT = os.path.dirname(os.path.abspath(__file__))
POSTS = os.path.join(PROJECT, "posts")

LINK_RE = re.compile(r"https?://public\.tableau\.com[^\s\"'<>)]+", re.I)
# Supported forms: /app/profile/U/viz/WB/VIEW, #!/vizhome/WB/VIEW,
# /views/WB/VIEW, and /vizhome/WB/VIEW.
VIZ_RE = re.compile(
    r"(?:/app/profile/[A-Za-z0-9_.-]+/viz"
    r"|#!/vizhome"
    r"|/(?:views|vizhome))"
    r"/([A-Za-z0-9_.:-]+)/([A-Za-z0-9_.:-]+)"
)


def clean_url(u: str) -> str:
    return u.rstrip(").,;").strip()


def parse_viz(u: str):
    m = VIZ_RE.search(u)
    if not m:
        return None, None
    return m.group(1), m.group(2)


def main():
    html_files = sorted(glob.glob(os.path.join(POSTS, "*.html")))
    items = []
    without = []
    dist = Counter()
    all_links = set()
    all_workbooks = set()

    for fn in html_files:
        stem = os.path.splitext(os.path.basename(fn))[0]
        txt = open(fn, encoding="utf-8", errors="replace").read()
        raw = [clean_url(m) for m in LINK_RE.findall(txt)]
        links = sorted(set(raw))  # Deduplicate links within each article.
        n = len(links)
        dist[n] += 1
        link_objs = []
        for l in links:
            all_links.add(l)
            wb, view = parse_viz(l)
            if wb:
                all_workbooks.add(wb)
            viz_url = f"https://public.tableau.com/views/{wb}/{view}" if wb else ""
            link_objs.append({
                "raw_url": l,
                "workbook": wb or "",
                "view": view or "",
                "viz_url": viz_url,
            })
        if n == 0:
            without.append(stem)
        items.append({
            "article": stem,
            "html_file": os.path.basename(fn),
            "link_count": n,
            "links": link_objs,
        })

    total = len(html_files)
    with_links = sum(1 for it in items if it["link_count"] > 0)
    summary = {
        "total_articles": total,
        "with_links": with_links,
        "without_links": total - with_links,
        "unique_links": len(all_links),
        "unique_workbooks": len(all_workbooks),
        "distribution": dict(sorted(dist.items())),
    }

    out_json = {
        "summary": summary,
        "items": items,
        "without_links": without,
    }
    with open(os.path.join(PROJECT, "public_links_map.json"), "w", encoding="utf-8") as f:
        json.dump(out_json, f, ensure_ascii=False, indent=2)

    # UTF-8 with BOM opens cleanly in Excel.
    with open(os.path.join(PROJECT, "public_links_map.csv"), "w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(["article", "seq", "workbook", "view", "raw_url", "viz_url"])
        for it in items:
            if it["link_count"] == 0:
                w.writerow([it["article"], "", "", "", "", ""])
            else:
                for i, lk in enumerate(it["links"], 1):
                    w.writerow([it["article"], i, lk["workbook"], lk["view"], lk["raw_url"], lk["viz_url"]])

    multi = [(it["article"], it["link_count"]) for it in items if it["link_count"] >= 2]
    lines = []
    lines.append("# Tableau Public Link Map Report\n")
    lines.append(f"> Source: `posts/*.html` ({total} articles) | Generated by `gen_links_map.py`\n")
    lines.append("## Summary\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Articles | {total} |")
    lines.append(f"| Articles with public links | {with_links} |")
    lines.append(f"| Articles without public links | {summary['without_links']} |")
    lines.append(f"| Unique public links | {summary['unique_links']} |")
    lines.append(f"| Unique workbooks | {summary['unique_workbooks']} |")
    lines.append("")
    lines.append("## Link count per article\n")
    lines.append("| Links | Articles |")
    lines.append("|---|---|")
    for k in sorted(dist):
        lines.append(f"| {k} | {dist[k]} |")
    lines.append("")
    lines.append(f"## Articles with at least two links ({len(multi)})\n")
    lines.append("| Article | Links |")
    lines.append("|---|---|")
    for a, c in multi:
        lines.append(f"| {a} | {c} |")
    lines.append("")
    lines.append("## Articles without public links\n")
    for a in without:
        lines.append(f"- {a}")
    lines.append("")
    lines.append("## Notes\n")
    lines.append("- `viz_url` is normalized as `https://public.tableau.com/views/{workbook}/{view}`.")
    lines.append("- See `public_links_map.json` for structured data and `public_links_map.csv` for the flat table.")
    with open(os.path.join(PROJECT, "public_links_report.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("OK")
    print("summary:", json.dumps(summary, ensure_ascii=False))
    print("multi-link articles:", len(multi))


if __name__ == "__main__":
    main()
